# Generated by Django 3.1.7 on 2021-03-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(blank=True, verbose_name='Номер варианта')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор ответа')),
                ('description', models.TextField(blank=True, max_length=1000000, null=True, verbose_name='Текст ответа')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='mainapp.question')),
            ],
        ),
    ]
