# Generated by Django 3.2.3 on 2021-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='description',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, max_length=1000000, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Автор ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='banner',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option',
            field=models.IntegerField(unique=True, verbose_name='Номер варианта'),
        ),
    ]
